name: js test
on: 
  issue_comment:
    types: [created, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/checkout.yml
      # - name: Hello world action step
      #   id: hello
      #   uses: '.github/actions'
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      #     branch: main
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"