name: Jira Add Comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - name: check out
        uses: actions/checkout@v3
      # nodejs 사용함
      - name: Use Node.js
        uses: actions/setup-node@v2
      # npm cache가 있으면 그거 씀
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      # github.secrets에 있는 token을 가져와서 js에 전달.
      - name: jira issue add comment by vercel deployed
        uses: bluelion2/jira-add-comment-action@master
        with:
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-url: ${{ 'https://freewheelin.atlassian.net/rest/api/3' }}
          jira-email: ${{ 'ksh0228@mathflat.com' }}
          comment-header: ${{ 'Preview Url' }}
