name: js test
on: 
  issue_comment:
    types: [created, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # git checkout
      - name: check out
        uses: actions/checkout@v3
      # nodejs 사용함
      - name: Use Node.js
        uses: actions/setup-node@v2

      # npm cache가 있으면 그거 씀
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      # js action 사용
      - name: jira test 
        run: |
          curl --request POST \
            --url 'https://freewheelin.atlassian.net/rest/api/3/issue/MATH2SP-431/comment' \
            --user 'ksh0228@mathflat.com:NaVvLkWLfhqzshZ4GLJX31DC' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget venenatis elit. Duis eu justo eget augue iaculis fermentum. Sed semper quam laoreet nisi egestas at posuere augue semper.",
                        "type": "text"
                      }
                    ]
                  }
                ]
              }
            }'

      # - name: Run My Actions 
      #   uses: ./
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}