name: js test
on: 
  issue_comment:
    types: [created, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: check out
      - run: ls al
      - uses: actions/checkout@v3
      - name: Run My Actions 
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: ${{ github.event.comment.body }}
          issue: ${{ github.event.issue.body }}
