name: js test
on: 
  issue_comment:
    types: [created, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # git checkout
      - name: check out
        uses: actions/checkout@v3
      # nodejs 사용함
      - name: Use Node.js
        uses: actions/setup-node@v2

      # npm cache가 있으면 그거 씀
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      # github.secrets에 있는 token을 가져와서 js에 전달.
      - name: Run My Actions 
        uses: ./.github/actions/
        with:
          jira-token: ${{secrets.JIRA_TOKEN}}