on:
  workflow_dispatch:
    
jobs:
  hello-my-actions:
    runs-on: ubuntu-latest
    name: Hello My Actions
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - name: Run My Actions 
        uses: ./ # 루트 디렉토리에 있는 액션을 사용하라는 의미이다.
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}