on:
  workflow_dispatch:
    
jobs:
  hello-my-actions:
    runs-on: ubuntu-latest
    name: Hello My Actions
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Run My Actions 
        uses: ./ # 루트 디렉토리에 있는 액션을 사용하라는 의미이다.
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}