# name: multi line test
# on:
#   issue_comment:
#     types: [created, edited]
# jobs: 
#   issue_test:
#     name: 'Issue_comment'
#     runs-on: ubuntu-latest
#     steps:
#       - name: create string
#         run: |
#           ISSUE=${{ github.event.issue.body }}
#           echo '-------'
#           COMMENT=${{ github.event.comment.body }}
#           echo '-------'
#           MY_STRING=${MY_STRING//'%'/'%25'}
#           MY_STRING=${MY_STRING//$'\n'/'%0A'}
#           MY_STRING=${MY_STRING//$'\r'/'%0D'}
          
#           # 변수 선언
#           echo "::set-output name=content::$ISSUE" 
#           echo "::set-output name=content::$COMMENT"
#            echo '-------'
#         id: my_string
#       - name: display string
#         run: |
#           echo "The string is: ${{ steps.my_string.outputs.content }}"


